version: '2'
services:
  techcorner:
    build: .
    container_name: techcorner
    ports:
      - "18080:8080"
      - "18787:8787"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    container_name: postgresdb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: techcorner